name: server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  registry: ghcr.io/john2143
  repo: openfrontpro_rs

jobs:
  create_docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    #- name: Download artifacts
      #uses: actions/download-artifact@v

    - name: Docker login
      run: |
        echo "${{ secrets.PAT_PACKAGES }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./rust/
        push: true
        tags: "${{ env.registry }}/${{ env.repo }}:${{ github.run_number }}"
        cache-from: type=gha
        cache-to: type=gha,mode=max

